### PR TITLE
fix issue #56

### PR DESCRIPTION
**Pull request by evle**

### CODE REVIEW

**Review by nezed — COMMENTED** [review]
@evle Thank for fixing it!
It would be great if you can add test for this case.
Please let me know if you need any help or experiencing any problems with it

**Comment by evle** [comment]
> @evle Thank for fixing it!
> It would be great if you can add test for this case.
> Please let me know if you need any help or experiencing any problems with it

testcase added

**Review by nezed — APPROVED** [review]
Thanks @evle !

**Comment by nezed** [comment]
@evle You fix is not available in version `@apla/clickhouse@1.6.4`

**Comment by evle** [comment]
> @evle You fix is not available in version `@apla/clickhouse@1.6.4`

is not available? any problems?

**Comment by nezed** [comment]
@evle Checked it just now - should be ok.
```
▶ npm logout

▶ npm i @apla/clickhouse@1.6.4
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ @apla/clickhouse@1.6.4
added 1 package from 1 contributor and audited 1 package in 0.424s
found 0 vulnerabilities

▶ grep WITH node_modules/@apla/clickhouse/src/clickhouse.js
	if (chQuery.match (/^(?:SELECT|WITH|SHOW|DESC|DESCRIBE|EXISTS\s+TABLE)/i)) {

```

Can you describe issue that you are experiencing?

**Comment by evle** [comment]
> @evle Checked it just now - should be ok.
> 
> ```
> ▶ npm logout
> 
> ▶ npm i @apla/clickhouse@1.6.4
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN test@1.0.0 No description
> npm WARN test@1.0.0 No repository field.
> 
> + @apla/clickhouse@1.6.4
> added 1 package from 1 contributor and audited 1 package in 0.424s
> found 0 vulnerabilities
> 
> ▶ grep WITH node_modules/@apla/clickhouse/src/clickhouse.js
> 	if (chQuery.match (/^(?:SELECT|WITH|SHOW|DESC|DESCRIBE|EXISTS\s+TABLE)/i)) {
> ```
> 
> Can you describe issue that you are experiencing?

#56

**Pull request merged**
