### PR TITLE
Fix encode arrays

### PR DESCRIPTION
**Pull request by orloffv**

### CODE REVIEW

**Comment by apla** [comment]
Patch changes whitespace characters, can’t see actual changes. Why not to write test for this bug?

**Comment by orloffv** [comment]
I'm sorry:) fixed

**Comment by orloffv** [comment]
@apla check test results without patch - https://travis-ci.org/apla/node-clickhouse/jobs/392865840

**Comment by apla** [comment]
Looks good! One more thing: can you check if CSV/TSV still works for arrays?

**Comment by nezed** [comment]
Looks good)

**Comment by j0tunn** [comment]
@orloffv looks like TSV is not working after this patch. On array ['qwerty'] it fails with an error
```
Error: Cannot parse input: expected [ before: qwerty\n...
```

**Comment by arman-oganesyan** [comment]
> @orloffv looks like TSV is not working after this patch. On array ['qwerty'] it fails with an error
> 
> ```
> Error: Cannot parse input: expected [ before: qwerty\n...
> ```

Yes, actually it doesn't work. Get the same error

`Cannot parse input: expected [ before:`

**Pull request merged**
